### ISSUE TITLE
[FR] Docker container 

### ISSUE THREAD

**Issue by Sloth-on-meth** [Run1e/STRIKER#2]
I would love to run this on docker on my Linux host. Do you have plans to create a container?

**Comment by sakgoyal** [comment]
if you look in the code, it already is a set of containers. but there isnt documentation on how to set it up yet.

**Comment by Run1e** [comment]
Hi there,

I don't have any immediate plans to uploading containers. They can created using the included Dockerfiles fairly easily, though.
