### ISSUE TITLE
Record options

### ISSUE THREAD

**Issue by MikaelPorttila** [Run1e/STRIKER#5]
Hi, Great work with the project so far!

One neat feature would be the option to pass settings such as crosshair and the cl_righthand 0 setting to reflects the players actual settings during the replay.

**Comment by 45O** [comment]
Pretty sure you're already aware of this now but, They've both been implemented however you need to be a patreon sub to access it

**Comment by Run1e** [comment]
Hi there,

This has been implemented a while ago. On the official instance it's a Patreon perk.

For selfhosted instances, you can simply override `get_tier` in cog.py to return `3` by default.
